#!/bin/bash

cd /var/www/html
rm ./index.html
#fullname=$(sed -n 2p _TAGME)
#cd /var/www/html/

echo '<link rel="stylesheet" href="./main.css">' >> ./index.html

echo "<h1>SITE AUTOMATICALLY UPDATES AT 00:00 UTC.</h1>" >> ./index.html

echo "<a href='./info.html'>Notifications<hr>: View recent announcments here." >> ./index.html

for f in `ls ./classes`
do
	cd /var/www/html
	descripti=$(sed -n 3p ./classes/$f/_TAGME)
	shortname=$(sed -n 1p ./classes/$f/_TAGME)
	echo "To Folder: <a href='./classes/$f/index.html'> $shortname</a><br>More Info: $descripti <hr>" >> ./index.html
	
	cd /var/www/html/classes/$f/
	./updatepage
done

cd - >> /dev/null
